modLoader="javafml"
loaderVersion="${javafml_version_range}"
license="MIT"
issueTrackerURL="https://github.com/${gh_organization}/${gh_repo_name}/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/${gh_organization}/${gh_repo_name}"
    updateJSONURL="https://raw.githubusercontent.com/${gh_organization}/${gh_repo_name}/1.16.x/update.json"
    authors="${mod_vendor}"
    description='''
A playground for learning Minecraft modding for 1.16.x
    '''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
